### ISSUE TITLE
Ruby 2.1.5 and 2.2.0: failed looking up symbols

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/osv-apps#22]
Hi folks,

The ruby app specifies 2.2.0, however, after building, there's a runtime symbol lookup failure for "__gmp_version"

Trying Ruby 2.1.5 yields "failed looking up symbol ruby_sysinit"

Cheers,

Rowland

**Comment by nyh** [comment]
On Tue, Apr 21, 2015 at 6:09 AM, Rowland Watkins <notifications@github.com>
wrote:

> Hi folks,
>
> The ruby app specifies 2.2.0, however, after building, there's a runtime
> symbol lookup failure for "__gmp_version"
>

Can someone familiar with the Ruby app please look into this? I can't even
build the Ruby image myself, because it requires the user to install Ruby
2.2.0 on the build machine, and I don't want to mess with the ruby
installation on my build machine :-(

As far as I can tell, the "__gmp_version" isn't something that OSv is
supposed to supply - it's supposed to come from libgmp, a library for
arbitrary-precision arithmetic, which I guess should be part of the image,
and I don't know why it is missing.


-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by nyh** [comment]
On Tue, Apr 21, 2015 at 8:48 AM, Nadav Har'El <nyh@cloudius-systems.com> wrote:
> On Tue, Apr 21, 2015 at 6:09 AM, Rowland Watkins <notifications@github.com>
> wrote:
>>
>> Hi folks,
>>
>> The ruby app specifies 2.2.0, however, after building, there's a runtime
>> symbol lookup failure for "__gmp_version"
>
>
> Can someone familiar with the Ruby app please look into this? I can't even
> build the Ruby image myself, because it requires the user to install Ruby
> 2.2.0 on the build machine, and I don't want to mess with the ruby
> installation on my build machine :-(
>
> As far as I can tell, the "__gmp_version" isn't something that OSv is
> supposed to supply - it's supposed to come from libgmp, a library for
> arbitrary-precision arithmetic, which I guess should be part of the image,
> and I don't know why it is missing.

CC'ing Takuya and Minoru.

- Pekka

**Comment by syuu1228** [comment]
Sorry for late reply, I requested Minoru to handle this issue but he haven't replied until now, probably he's busy.

Rowland, could you tell us following informations:
- console output when you build & execute OSv
- Linux distribution 
- How did you install Ruby 2.1.5 on Linux

**Comment by rowlandwatkins** [comment]
No worries, here's my environment:

Host OS: Ubuntu 14.10
Ruby: 2.1.5, 2.2.0 via RVM
Console Output (2.2.0):

[[[
Created instance: riemann-dash
OSv v0.09-1825-ge63c2c9
eth0: 192.168.122.62
/libruby.so.2.2: failed looking up symbol __gmp_version

[backtrace]
0x000000000034366d <elf::object::symbol(unsigned int)+205>
0x0000000000395a34 <elf::object::arch_relocate_rela(unsigned int, unsigned int, void*, long)+292>
0x0000000000341e54 <elf::object::relocate_rela()+148>
0x0000000000344257 <elf::object::relocate()+199>
0x0000000000347320 <elf::program::load_object(std::string, std::vector<std::string, std::allocator<std::string> >, std::vector<std::shared_ptr<elf::object>, std::allocator<std::shared_ptr<elf::object> > >&)+1600>
0x0000000000346632 <elf::object::load_needed(std::vector<std::shared_ptr<elf::object>, std::allocator<std::shared_ptr<elf::object> > >&)+402>
0x0000000000347317 <elf::program::load_object(std::string, std::vector<std::string, std::allocator<std::string> >, std::vector<std::shared_ptr<elf::object>, std::allocator<std::shared_ptr<elf::object> > >&)+1591>
0x0000000000347cd1 <elf::program::get_library(std::string, std::vector<std::string, std::allocator<std::string> >)+241>
0x000000000042022a <osv::application::application(std::string const&, std::vector<std::string, std::allocator<std::string> > const&)+442>
0x00000000004209c7 <osv::application::run(std::string const&, std::vector<std::string, std::allocator<std::string> > const&)+87>
0x0000000000420bd6 <osv::application::run(std::vector<std::string, std::allocator<std::string> > const&)+22>
0x0000000000213e79 <do_main_thread(void*)+1801>
0x000000000044b065 <???+4501605>
0x00000000003f0337 <thread_main_c+39>
0x0000000000391fa5 <???+3743653>
]]]

I'll need to rebuild for 2.1.5, so I'll get back to you

**Comment by cosmo0920** [comment]
I've got a same issue with following patch (Bump up Ruby 2.2.2):

 ```diff
diff --git a/ruby/Makefile b/ruby/Makefile
index 4e83d90..b242e0d 100644
--- a/ruby/Makefile
+++ b/ruby/Makefile
@@ -3,7 +3,7 @@ module: version_check ruby.so usr.manifest
 
 CFLAGS=-fPIC -Wall -shared
 
-RUBY_VER=2.2.0
+RUBY_VER=2.2.2
 
 RUBY_LDFLAGS=-lm -lcrypt -ldl -lpthread -lruby
 LIBS=-Lupstream/ruby
```

Host OS: Ubuntu 14.04.2 amd64
Ruby 2.2.0, 2.2.2 via rbenv
Console Output (2.2.2):

```log
% ./scripts/run.py -e "/ruby.so /irb" 
OSv v0.21-2-g6a39937
eth0: 192.168.122.15
/libruby.so.2.2: failed looking up symbol __gmp_version

[backtrace]
0x0000000000344430 <elf::object::symbol(unsigned int)+208>
0x0000000000395b76 <elf::object::arch_relocate_rela(unsigned int, unsigned int, void*, long)+214>
0x0000000000341523 <elf::object::relocate_rela()+147>
0x0000000000343127 <elf::object::relocate()+199>
0x0000000000346753 <elf::program::load_object(std::string, std::vector<std::string, std::allocator<std::string> >, std::vector<std::shared_ptr<elf::object>, std::allocator<std::shared_ptr<elf::object> > >&)+1635>
0x0000000000345a72 <elf::object::load_needed(std::vector<std::shared_ptr<elf::object>, std::allocator<std::shared_ptr<elf::object> > >&)+402>
0x000000000034674a <elf::program::load_object(std::string, std::vector<std::string, std::allocator<std::string> >, std::vector<std::shared_ptr<elf::object>, std::allocator<std::shared_ptr<elf::object> > >&)+1626>
0x0000000000346fcb <elf::program::get_library(std::string, std::vector<std::string, std::allocator<std::string> >)+251>
0x000000000041542b <osv::application::application(std::string const&, std::vector<std::string, std::allocator<std::string> > const&)+459>
0x0000000000415b74 <osv::application::run(std::string const&, std::vector<std::string, std::allocator<std::string> > const&)+100>
0x0000000000415d96 <osv::application::run(std::vector<std::string, std::allocator<std::string> > const&)+22>
0x0000000000213061 <do_main_thread(void*)+2449>
0x000000000043fac5 <???+4455109>
0x00000000003efe97 <thread_main_c+39>
0x0000000000391da5 <???+3743141>
```

**Comment by nyh** [comment]
On Sat, Jun 6, 2015 at 10:47 PM, Hiroshi Hatake <notifications@github.com>
wrote:

> I've got a same issue with following patch (Bump up Ruby 2.2.2):
>

Unfortunately, I can't check the ruby app myself because I don't have a
recent-enough Ruby *installed* on my system (I wish that one day someone
will solve this dependency).

So I can only ask questions...


> failed looking up symbol __gmp_version
>
>
Sounds like Ruby needs libgmp.so, but for some reason, either wasn't
compiled with it as a dependency, or it's not on the image. Can you please
do me a favor and:

1. Run "run.py -V" (verbose mode) to see if it warns about missing shared
objects?
2. run "ldd ROOTFS/ruby.so", to see if it properly lists its dependency on
libgmp.so?
3. Show me your "usr.manifest" - which libraries it is copying to the image

Thanks,
Nadav.

**Comment by cosmo0920** [comment]
`run.py -V -e "/ruby.so /irb" result:

```log
OSv v0.21-3-g0ff6451
4 CPUs detected
Firmware vendor: Bochs
bsd: initializing - done
VFS: mounting ramfs at /
VFS: mounting devfs at /dev
RAM disk at 0x0xffff8000027b9040 (4096K bytes)
net: initializing - done
vga: Add VGA device instance
eth0: ethernet address: 52:54:00:12:34:56
virtio-blk: Add blk device instances 0 as vblk0, devsize=10737418240
random: virtio-rng registered as a source.
random: intel drng, rdrand registered as a source.
random: <Software, Yarrow> initialized
VFS: unmounting /dev
VFS: mounting zfs at /zfs
zfs: mounting osv/zfs from device /dev/vblk0.1
random: device unblocked.
VFS: mounting devfs at /dev
VFS: mounting procfs at /proc
program zpool.so returned 1
BSD shrinker: event handler list found: 0xffffa00001a47480
	BSD shrinker found: 1
BSD shrinker: unlocked, running
[I/43 dhcp]: Waiting for IP...
[I/246 dhcp]: Server acknowledged IP for interface eth0
eth0: 192.168.122.15
[I/246 dhcp]: Configuring eth0: ip 192.168.122.15 subnet mask 255.255.255.0 gateway 192.168.122.1 MTU 1500
could not load libgmp.so.10
could not load libcrypt.so.1
/libruby.so.2.2: failed looking up symbol __gmp_version

[backtrace]
0x0000000000344430 <elf::object::symbol(unsigned int)+208>
0x0000000000395b76 <elf::object::arch_relocate_rela(unsigned int, unsigned int, void*, long)+214>
0x0000000000341523 <elf::object::relocate_rela()+147>
0x0000000000343127 <elf::object::relocate()+199>
0x0000000000346753 <elf::program::load_object(std::string, std::vector<std::string, std::allocator<std::string> >, std::vector<std::shared_ptr<elf::object>, std::allocator<std::shared_ptr<elf::object> > >&)+1635>
0x0000000000345a72 <elf::object::load_needed(std::vector<std::shared_ptr<elf::object>, std::allocator<std::shared_ptr<elf::object> > >&)+402>
0x000000000034674a <elf::program::load_object(std::string, std::vector<std::string, std::allocator<std::string> >, std::vector<std::shared_ptr<elf::object>, std::allocator<std::shared_ptr<elf::object> > >&)+1626>
0x0000000000346fcb <elf::program::get_library(std::string, std::vector<std::string, std::allocator<std::string> >)+251>
0x000000000041542b <osv::application::application(std::string const&, std::vector<std::string, std::allocator<std::string> > const&)+459>
0x0000000000415b74 <osv::application::run(std::string const&, std::vector<std::string, std::allocator<std::string> > const&)+100>
0x0000000000415d96 <osv::application::run(std::vector<std::string, std::allocator<std::string> > const&)+22>
0x0000000000213061 <do_main_thread(void*)+2449>
0x000000000043fac5 <???+4455109>
0x00000000003efe97 <thread_main_c+39>
0x0000000000391da5 <???+3743141>
```

`ldd ROOTFS/ruby.so` result:

```log
	linux-vdso.so.1 =>  (0x00007ffd6b292000)
	libruby.so.2.2 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007facdce56000)
	/lib64/ld-linux-x86-64.so.2 (0x00007facdd45f000)
```

Unfortunately, it seems not to list dependency on libgmp.so.

My `usr.manifest` is as follows:

```log
/ruby.so: ${MODULE_DIR}/ruby.so
/**: ${MODULE_DIR}/upstream/ruby/bin/**
/libruby.so.2.2: ${MODULE_DIR}/upstream/ruby/libruby.so
/usr/lib/ruby/2.2.0/**: ${MODULE_DIR}/upstream/ruby/lib/**
/usr/lib/ruby/2.2.0/x86_64-linux/rbconfig.rb: ${MODULE_DIR}/upstream/ruby/rbconfig.rb
/usr/lib/ruby/2.2.0/x86_64-linux/**: ${MODULE_DIR}/upstream/ruby/.ext/x86_64-linux/**
/usr/local/ssl/cert.pem: ${MODULE_DIR}/upstream/cert.pem
libcrypto.so.1.0.0: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
libffi.so.6: /usr/lib/x86_64-linux-gnu/libffi.so.6
libreadline.so.6: /lib/x86_64-linux-gnu/libreadline.so.6
libssl.so.1.0.0: /lib/x86_64-linux-gnu/libssl.so.1.0.0
libtinfo.so.5: /lib/x86_64-linux-gnu/libtinfo.so.5
libyaml-0.so.2: /usr/lib/x86_64-linux-gnu/libyaml-0.so.2
libz.so.1: /lib/x86_64-linux-gnu/libz.so.1
```

**Comment by nyh** [comment]
On Sun, Jun 7, 2015 at 3:16 PM, Hiroshi Hatake <notifications@github.com>
wrote:

> `run.py -V -e "/ruby.so /irb" result:
>
> could not load libgmp.so.10
> could not load libcrypt.so.1
> /libruby.so.2.2: failed looking up symbol __gmp_version
>
>
So the problem is that libgmp.so.10 was expected, and missing, on the image.
We should probably make the "could not load..." messages more verbose, and
not only shown on verbose run.


> ldd ROOTFS/ruby.so result:
>
>     linux-vdso.so.1 =>  (0x00007ffd6b292000)
>     libruby.so.2.2 => not found
>     libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007facdce56000)
>     /lib64/ld-linux-x86-64.so.2 (0x00007facdd45f000)
>
> Unfortunately, it seems not to list dependency on libgmp.so.
>

Yes, probably libgmp.so is a dependency of libruby.so.2.2.

The code in Makefile does "ldd" on every file in
upstream/ruby/.ext/x86_64-linux/ to find needed libraries, but does NOT ldd
upstream/ruby/libruby.so, where this libruby.so.2.2 apparently is.

Can you please try to change the Makefile line (it seems there are two)

which does

     find upstream/ruby/.ext/x86_64-linux/

To do something like
    find upstream/ruby

(or something more refined...) and see if it fixes the problem? If it does,
can you please send a patch? Thanks.


-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by cosmo0920** [comment]
Sorry late response, I've submitted patch #32.

> Yes, probably libgmp.so is a dependency of libruby.so.2.2.

You are right. libruby.so.2.2 depends `libgmp.so` and `libcrypt.so`.
They are concealed:

```log
% ldd ruby/ruby.so   
        ...
	libruby.so.2.2 => not found
```

`libruby.so.2.2` is placed in `ruby/upstream/ruby/libruby.so.2.2`.


```log
% ldd ruby/upstream/ruby/libruby.so.2.2
	linux-vdso.so.1 =>  (0x00007ffce1cd8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2a191bf000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f2a18f4a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2a18d46000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f2a18b0d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2a18807000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2a18441000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2a198f2000)
```

This output is also needed to construct correct `usr.nmanifest`.

**Comment by cosmo0920** [comment]
Now, osv-apps/ruby's Makefile uses built `libruby.so.2.2`.
It seems to be this line: https://github.com/cloudius-systems/osv-apps/blob/f342b8df8c58a72b6f01e878fb3f774e5792a59d/ruby/Makefile#L17-L18 is needless.
Without this lines, it does not break shared object consistency.

What do you think of that, @orumin?

**Comment by orumin** [comment]
I think so that.
Thanks for report and I will send patch that soon.

**Comment by nyh** [comment]
I can reproduce the same problem.

The problem appears to be that I had previously build apps/ruby on an older distribution and older ruby, and the old usr.manifest apparently stayed behind, and no longer was correct (it didn't list libgmp). Doing "cd apps/ruby; make clean", or more drastically, "scripts/build clean" (to clean all modules) fixed this problem. So it's not a real bug.

Running Ruby still fails, but it's no longer the libgmp thing.
