### ISSUE TITLE
Move images/*.py and config.json to apps repository

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv-apps#4]
If you look at images/{cassandra,rogue,tomcat}.y, they only say they contain themselves. This file should only be necessary if it needs to specify something non-obvious.

But more importantly, why is images/*.py in the main OSv repository? It should be in the apps repository.

Config.json should also be in the apps repository.
We can read _both_ osv/config.json and osv/apps/config.json, to allow both Takuya's original method and the new apps/ method to work.

**Comment by geraldo-netto** [comment]
Dear @nyh , @wkozaczuk ,

I think this ticket is outdated, right?

Kind Regards,
Geraldo Netto

**Comment by wkozaczuk** [comment]
I am not sure it is outdated. The config.json, images directory and its both files are still used by build process. But at this point I am not sure how important it is to move those to apps repo. Feel free to experiment with it and see what changes would have to be made to ./scripts/module.py and other Python build programs.

**Comment by nyh** [comment]
The first part of this issue is completely outdated - we no longer use the images/ directory to specify entire images, and instead compose images given a list of "modules" (subdirectories in modules/, apps/, or any other directory specified in config.json).

The second point, that config.json is in the top-level directory, is not entirely outdated, although I suspect that when I wrote this issue, config.json had to list individual modules, or something, because as it stands, I don't see a problem with the top-level config.json just mentioning the directory "apps".

So I'm closing this issue. If we feel there is still a problem here, we can reopen an issue - probably in the main OSv bug tracker and not here.
