### ISSUE TITLE
add cado to perl stack

### ISSUE THREAD

**Issue by russt** [cloudius-systems/osv-apps#43]
Now that we have perl, I would like to add cado, which is a general purpose code-generation language based on perl:
- cado - will provide cado-base (from perl-base)
- cado-test - test suite for cado (from cado-base)

The cado-test suite provides an good aplication level test suite for perl-base.

The cado project is hosted on github and sourceforge:
- https://github.com/russt/cado
- http://sourceforge.net/projects/cado

**Comment by geraldo-netto** [comment]
Dear @russt , @nyh , @wkozaczuk , All,

I think we should close this ticket once we already have Cado support (Perl is embedded):
https://github.com/cloudius-systems/osv-apps/tree/master/cado


Kind Regards,
Geraldo Netto

**Comment by wkozaczuk** [comment]
Indeed I have built the cado image and ran it (it printed some cado verbiage). Therefore I am considering that this ticket can be closed.
