### ISSUE TITLE
Java and other stuff should be optional

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv-apps#5]
Right now, "make image=rogue" creates an image with rogue, but also Java, tests/*, and a whole lot of other irrelevant stuff.

We should make "tests" and "java" modules of their own, and for example have the "default" module depend on "tests", the "mgmt" module depend on "java", and similarly the "tomcat" module depends on "java" - but "rogue" does NOT depend on java.

**Comment by geraldo-netto** [comment]
Dear @nyh/@wkozaczuk,

Is it still valid?
If so, could you point out how you would envision the modular/optional build?


Kind Regards,
Geraldo Netto

**Comment by nyh** [comment]
I'm closing this issue, it's outdated. "make image=rogue" now includes only rogue and a few small tools (for formatting the disk and such) - it does not include java, tests, etc. We basically did already exactly what was requested, but forgot to close this issue.
