### ISSUE TITLE
[bug] iperf-zcopy cannot be built out of the box

### ISSUE THREAD

**Issue by jmmlmendes** [cloudius-systems/osv-apps#51]
iperf-zcopy fails to build because both zcopy-rx.diff and zcopy-tx.diff patches fail to apply.
The reason they fail to apply is because the iperf source files contain trailing whitespaces while the patches don't. As I see there are 2 solutions:
1) Add missing trailing whitespaces to the patches (though I wouldn't call something that adds useless characters at end of lines a clean solution)
2) A more elegant solution is, IMHO, to remove trailing whitespaces from the files to be patched before applying the patches. I'll submit a pull request with this change shortly

**Comment by nyh** [comment]
Thanks. Would the "--ignore-whitespace" option to "patch" have worked instead?
But I'll apply your fix. Looks good enough to me. I wonder how we didn't see this problem before.

**Comment by jmmlmendes** [comment]
You're absolutely right, I overlooked the simplest solution...
Anyway, I'll close the issue since the bug was fixed.
