### ISSUE TITLE
httpserver-html5-cli depends on missing libhttpserver.so

### ISSUE THREAD

**Issue by kubrickfr** [cloudius-systems/osv-apps#59]
When I build my image with 
./scripts/build image=openjdk8-zulu-full,tomcat,httpserver-html5-cli

I get the following error message at launch:
```
Failed to load object: /libhttpserver.so. Powering off.
```
This particular .so is nowhere to be found in in the directory tree.

**Comment by wkozaczuk** [comment]
We do not do pull requests so I would kindly ask you to send us git patch to https://groups.google.com/forum/#!forum/osv-dev following these guidelines - https://github.com/cloudius-systems/osv/wiki/Formatting-and-sending-patches.
